### ISSUE TITLE
Doesn't work with Python 3.5?

### ISSUE THREAD

**Issue by picandocodigo** [s1cp/nxshot#47]
I'm not a Python programmer, so I'm sorry if this issue is not exactly right. I got this error while trying to run the script with Python 3.5:
```
Traceback (most recent call last):
  File "nxshot.py", line 8, in <module>
    from Crypto.Cipher import AES
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/AES.py", line 50, in <module>
    from Crypto.Cipher import _AES
ImportError: cannot import name '_AES'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "nxshot.py", line 8, in <module>
    from Crypto.Cipher import AES
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/AES.py", line 50, in <module>
    from Crypto.Cipher import _AES
ImportError: cannot import name '_AES'
```

**Python version:** `3.5.2`
**OS:** `Ubuntu 18.04.1`

[Is this issue related to the error?](https://github.com/dlitz/pycrypto/issues/238)
Cheers!

**Comment by Querschlag** [comment]
You can use PyCryptodome as a drop in replacement for pycrypto.
Just `pip install pycryptodome`. No need to adjust the imports.
